[project]
name = "asyncpg-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.31.0",
    "ipykernel>=7.1.0",
    "pydantic[email]>=2.12.5",
    "pydantic-settings>=2.12.0",
    "sqlparse>=0.5.4",
    "passlib[argon2]>=1.7.4",
    "pogo-migrate>=0.3.3",
    "fastapi[all]>=0.128.0",
    "pyjwt>=2.10.1",
    "fractional-indexing>=0.1.3",
    "aioboto3>=15.5.0",
    "mypy-boto3-s3>=1.42.37",
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "asgi-lifespan>=2.1.0",
    "redis>=7.1.1",
    "pypika>=0.51.1",
    "python-slugify>=8.0.4",
    "mypy-boto3-ses>=1.43.0",
]

[tool.pogo]
migrations = './migrations'
database_config = '{POGO_DATABASE}'

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "session"
asyncio_default_test_loop_scope = "session"

[tool.ruff.format]
skip-magic-trailing-comma = true
